DROP TABLE IF EXISTS Account;
DROP TABLE IF EXISTS Budget_Category;
DROP TABLE IF EXISTS Budget;
DROP TABLE IF EXISTS Transaction_Category;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS [Transaction];
DROP TABLE IF EXISTS [User];